#ifndef LECTURES_CODE_STATIC_NO_CLASSES_ODR_VIOLATION_OUR_COOL_LIB_HPP
#define LECTURES_CODE_STATIC_NO_CLASSES_ODR_VIOLATION_OUR_COOL_LIB_HPP

void SayHello();  // 😱 This really should be inline

#endif /* LECTURES_CODE_STATIC_NO_CLASSES_ODR_VIOLATION_OUR_COOL_LIB_HPP */
