name: Checks

on: push

jobs:
  markdown-link-check:
    name: All Markdown links are valid
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Run linkspector
       uses: umbrelladocs/action-linkspector@v1
       with:
         reporter: github-pr-review
         fail_level: any
         config_file: .github/.linkspector.yml

  check-snippet-compilation:
    name: All code snippets compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check that all snippets compile
      run: |
        pip install pipenv
        cd scripts
        pipenv install
        pipenv run python3 validate_code_snippets.py --project-folder ../
