name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    name: All Markdown links are valid
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  
  check-snippet-compilation:
    name: All code snippets compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check that all snippets compile
      run: python3 scripts/validate_code_snippets.py
